# @author Jeff Carpenter
name: Stargate Postman Collections

# runs on
# * manual trigger
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:

  # Runs Stargate Postman Collections against local Stargate instance using docker compose scripts
  automated-api-tests:
    runs-on: ubuntu-latest
    strategy:

      # let all tests run, can find multiple failures in different apis
      fail-fast: false

      # props:
      # backend - cassandra backend to run
      # collection - Postman collection to run

      matrix:
        backend: [ cassandra-40, cassandra-311, dse-68 ]
        collection: [ docsapi-library, graphqlapi-library, restapi-users ]
        include:
          - backend: cassandra-40
            path: docker-compose/cassandra-4.0
          - backend: cassandra-311
            path: docker-compose/cassandra-3.11
          - backend: dse-68
            path: docker-compose/dse-6.8
          - collection: docsapi-library
            collection-id: 12949543-caba2a02-6559-486a-9e4a-d5c0791fd296
            environment-id: 12949543-2e78cf27-bd8c-43f2-909f-70a2b87d65fe
            service: docsapi
          - collection: graphqlapi-library
            collection-id: 17930693-65da5c64-561a-449b-a0e8-0318575f6871
            environment-id: 12949543-2e78cf27-bd8c-43f2-909f-70a2b87d65fe
            service: graphqlapi
          - collection: restapi-users
            collection-id: 17930693-47ab5f0d-407e-48cf-aa11-c51d129f1eef
            environment-id: 12949543-2e78cf27-bd8c-43f2-909f-70a2b87d65fe
            service: restapi
    steps:
      - uses: actions/checkout@v4
      - name: Start Backend
        # Run Stargate coordinator in developer mode to save time / resources, and only the API under test
        run: |
          cd ${{ matrix.path }}
          docker compose -f docker-compose-dev-mode.yml up -d --wait coordinator ${{ matrix.service }}
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: |
          postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API test
        run: |
          postman collection run ${{ matrix.collection-id }} -e ${{ matrix.environment-id }} \
          --env-var POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY }} --verbose
      - name: Stop Backend
        if: always()
        run: |
          cd ${{ matrix.path }}
          docker compose logs ${{ matrix.service }}
          docker compose -f docker-compose-dev-mode.yml down

